service: AWS-KMS-SelfLearning

provider:
  name: aws
  runtime: java8
  region: ap-southeast-2
  versionFunctions: false
  profile: tw-aws-beach

  iamRoleStatements:
    - Effect: Allow
      Action:
        - kms:*
        - lambda:InvokeFunction
      Resource: "*"

package:
  artifact: build/libs/hello-kms.jar

functions:
  LambdaToEncryptAndDecrypt:
    handler: lambda.Lambda1
    timeout: 900
    reservedConcurrency: 100

resources:
  Resources:
    RSASigningKey:
      Type: AWS::KMS::Key
      Properties:
        Description: RSA_4096 asymmetric CMK
        KeySpec: RSA_4096
        KeyUsage: ENCRYPT_DECRYPT
        KeyPolicy:
          Version: '2012-10-17'
          Id: key-default-2
          Statement:
            - Sid: Enable IAM User Permissions
              Effect: allow
              Principal:
                AWS:
                  - arn:aws:iam::160071257600:root
                  - arn:aws:iam::160071257600:role/PowerUserPlusRole
              Action: kms:*
              Resource: '*'
              Condition:
                StringNotEquals:
                  kms:EncryptionAlgorithm: RSAES_OAEP_SHA_256

#    SymmetricEncryption:
#      Type: AWS::KMS::Key
#      Properties:
#        Description: An example symmetric CMK
#        EnableKeyRotation: true
#        PendingWindowInDays: 20
#        KeyPolicy:
#          Version: '2012-10-17'
#          Id: key-default-1
#          Statement:
#            - Sid: Enable IAM User Permissions
#              Effect: Allow
#              Principal:
#                AWS: arn:aws:iam::160071257600:root
#              Action: kms:*
#              Resource: '*'